name: 'security-devops-action'
description: 'Run security analyzers.'
author: 'Microsoft'
branding:
  icon: 'shield'
  color: 'black'
inputs:
  config:
    description: A file path to a .gdnconfig file.
  policy:
    description: The name of the well known policy to use. Defaults to Microsoft.
    default: Microsoft
outputs:
  sarifFile:
    description: A file path to a SARIF results file.
runs:
  using: 'node12'
  main: 'lib/action.js'