# pull request action verification

name: MSDO on-push-verification windows-latest
on: push

jobs:
  sample:
    name: Microsoft Security DevOps Analysis

    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

      # Run open source static analysis tools
    - name: Run Microsoft Security DevOps Analysis
      uses: ./
      id: msdo

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
