name: MSDO ubuntu-latest
on:
  push:
    branches:
      - main

jobs:
  sample:
    name: Microsoft Security DevOps Analysis

    # MSDO runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: ubuntu-latest

    steps:
      
      # Checkout your code repository to scan
    - uses: actions/checkout@v2

      # Install dotnet, used by MSDO
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

      # Run static analysis tools
    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@main
      id: msdo

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
